apiVersion: v1
items:
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: docker-image-service-a-v2
  spec:
    params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/demo/springboot-ol-service-a:2.0.2
    type: image
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: git-source-service-a-v2
  spec:
    params:
    - name: revision
      value: v2
    - name: url
      value: https://github.com/My-Appsody-Org/service-a
    type: git
kind: List
